services:
  postgres_db_dev:
    image: postgres:16.4-alpine3.20
    ports:
      - "5432:5432"
    env_file:
      - ../envs/postgres.env
    volumes:
      - postgres_dev:/var/lib/postgresql/data
volumes:
  postgres_dev:
