function useSelectedStrings() {
    const selectedStrings = {
        daysOfWeeks: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        loaderTexts: [
            "Connecting to Server",
            "Loading data please wait",
            "We appreciate your patience",
        ],
        sidebarHeading: "TalkTune",
        active: "Active",
        actSetting: "Account Settings",
        btnSignin: "Sign In",
        btnSignup: "Sign Up",
        btnLogout: "Logout",
        btnResetPw: "Send password reset link",
        btnInterview: "Start",
        btnBuyTokens: "Buy Tokens",
        btnDismiss: "Dismiss",
        changeCard: "Change card details",
        btnInterEval: "Evaluate Interview",
        btnRepeat: "Repeat",
        btnEnd: "End",
        btnPause: "Pause",
        btnResume: "Resume",
        btnClose: "Close",
        btnShare: "Share",
        btnBack: "Go back",
        backBtn: "Back",
        btnBack2: "Back",
        btnChangePw2: "Change my password",
        btnSave: "Save & Submit",
        btnChangePw: "Change Password",
        btnLink: "Link",
        btnDelAcc: "Delete",
        btnUnsubscribe: "Unsubscribe",
        btnUpdate: "Update",
        btnCancel: "Cancel",
        btnEvaluate: "Evaluate",
        errorTitle: "Something went wrong",
        errorDescription: "Error while loading content",
        errorButton: "Try again",
        labelLogin: "Login",
        labelEmail: "Email",
        labelPassword: "Password",
        labelOldPassword: "Old Password",
        labelNewPassword: "New Password",
        labelFirstName: "First Name",
        labelLastName: "Last Name",
        labelMobile: "Mobile",
        labelProfileImage: "Profile Image",
        profileTitle: "Profile",
        apiTitle: "API Configuration",
        billingTitle: "Billing and Subscription",
        cancelSubscription: "Cancel Subscription",
        labelForgetPw: "Forget Password?",
        labelDonotHaveAcc: "Don't have an account",
        labelSigninWithGoogle: "Sign in with Google",
        labelSignupWithGoogle: "Sign up with Google",
        labelViewResults: "View full result",
        labelBuySessions: "Buy more sessions",
        notFoundTitle: "Page Not Found",
        notFoundDescription:
            "Requested page not found. Would you like to return to home page?",
        notFoundButton: "Go to home page",
        textWords: "Words",
        textWpm: "wpm",
        textScore: "Score",
        textLow: "Low",
        textAverage: "Average",
        textHigh: "High",
        textTooMany: "Too Many",
        textClarity: "Clarity",
        textRepetitions: "Top repetitions",
        textInter: "Interview",
        textNotification: "Notifications",
        textStreak: "Streak",
        textToken: "Token",
        textFaq: "FAQ",
        textSupport: "Support",
        textNext: "Next",
        textAdd: "Add",
        textDashboard: "Dashboard",
        textChats: "Chats",
        textMeeting: "Meetings",
        textSettings: "Settings",
        textMyReports: "Reports",
        textHome: "Home",
        textMale: "Male",
        textFemale: "Female",
        textYes: "Yes",
        textNo: "No",
        textOK: "OK",
        textTryAgain: "Try Again",
        textCancel: "Cancel",
        textConfirm: "Confirm",
        textAccount: "Account",
        textGeneral: "General",
        textBilling: "Billing",
        textPreferences: "Preferences",
        textName: "Name",
        textWord: "Word",
        textAbout: "About",
        textDisplay: "Display",
        textDays: "Days",
        textAnswer: "Answer",
        textMarks: "Marks",
        textAspect: "Aspect",
        textFeedback: "Feedback",
        textMistake: "Mistake",
        textClarification: "Clarification",
        textCorrection: "Correction",
        textEnable: "Enable",
        textMode: "Mode",
        textOverallFeedback: "Overall Feedback",
        textEvaluating: "Evaluating....",
        textQuestionTokens: "question_tokens",
        textHomeSimple: "home",
        textReportSimple: "report",
        textReportsSimple: "reports",
        textSettingsSimple: "settings",
        textPasswordResetSimple: "settings/password-reset",
        textHourSimple: "hour",
        textMinSimple: "min",
        textSecSimple: "sec",
        textLeftSimple: "left",
        textFiveMin: "5 min",
        textTenMin: "10min",
        textFifteenMin: "15min",
        textBillingHistory: "Billing History",
        textColorGreen: "green",
        textColorRed: "red",
        textColorYellow: "yellow",
        textColorOrange: "orange",
        textTalkTime: "Talk Time",
        textFillerWords: "Filler Words",
        textRepetitiveWords: "Repetitive Words",
        textAhCount: "Ah Count",
        textKeyMatrix: "Key Matrix",
        textPronounciation: "Pronounciation & Fluency",
        textPase: "Word Pace(WPM)",
        textPaseSlow: "Slow",
        textPaseNormal: "Normal",
        textPaseHard: "Hard to understand",
        textQuestionAsked: "Question Asked",
        textRareWords: "Rare words",
        textUniqueWords: "Unique words",
        textContactUs: "Contact Us",
        textThisWeek: "In this week",
        textPrivacyPolicy: "Privacy Policy",
        textTermsConditions: "Terms & Conditions",
        textDelAcc: "Delete Account",
        textCurrentPlan: "Current Plan",
        textAIAnalyser: "AI Analyser",
        textInsights: "Insights",
        textHeaderInterNode: "NodeJS Speaking Interviews",
        textHeaderInterIelts: "IELTS Speaking Interviews",
        textHeaderInterRandom: "Random Interviews",
        textHeaderInterProject: "Project Manager Interviews",
        textSpeakerSelect: "Select your character",
        textMicrphoneSelect: "Select your microphone",
        textRedirectMsg: "We are redirecting you to our portal",
        textTryAnInterview: "Try for an interview to measure your progress..",
        textAccCreated: "Account created...",
        textSignupAlmost: "You are almost there...",
        textAccAlreadyHave: "Already have an account?",
        textWaiting: "Please wait...",
        textWaitForResults: "Wait few more seconds to your results",
        textInfoGathering: "We are gathering your information",
        textPrepareInterview: "We are preparing your interview...",
        textPersonalReview: "Review your overall performance",
        textInterAnalize: "Analyzing your interview",
        textMoreTokens: "Need more tokens",
        topUpTokens: "Top up your tokens",
        textTryMonthlySub: "Try Monthly Subscription",
        textTalkAbout: "What others say about TalkTune",
        textSelectAudioInput: "Select Audio Input Device",
        textInterLoading: "We are almost there",
        textInterPrepare: "We're just preparing your interview",
        textInterviewThanks:
            "Thanks for waiting! We're gearing up for your interview now",
        textInterviewStart:
            "The countdown begins! Your interview is getting started",
        textInterEval: "We're just Evaluating your interview",
        textQuesPrepare: "We're just preparing your questions...",
        textonboardingSkills: `Help us create our feedback report, so you can learn better insights on your improvement`,
        textLastInterSummary: "Last interview feedback summary",
        textInterAnalysis: "Interview Analysis",
        textInterSummary: "Summary",
        textInterHistory: "Interview History",
        textThingsToImprove: "Things to improve",
        textWhatsGood: "Things you did well",
        textFilterWords: "Top Filler words",
        textTimeLeft: "Time Left",
        textTimePassed: "Time passed",
        textReady: "Get Ready...",
        textTakeBreath: "Take a breath",
        textNotEnoughTokens: "No enough tokens",
        textBuyMoreTokens: "Buy more tokens to start interview",
        textEvaluateInterviewConfirm:
            "Are you sure you want to evaluate this interview?",
        textDeleteInterviewConfirm: "Are you sure you want to delete your account?",
        textDeletePInterviewConfirm:
            "And all your data will be deleted permanently.",
        textCancelSubscriptionConfirm:
            "Are you sure you want to cancel your subscription?",
        textRenewSubscriptionConfirm:
            "Are you sure you want to renew your subscription?",
        textEvaluateInterviewHeading: "Evaluate Interview",
        textBuyTokensToEvaluate:
            "Buy more tokens to evaluate the interview and generate insightful reports.",
        textBuyTokensToInterview: "Buy more tokens to interview in artificial mode",
        textDurationInterview: "Duration of the Interview",
        textInterviewEvaluate:
            "Interview is not evaluated yet. Evaluate to see results.",
        textDelConfirm: "Are you sure to delete your account?",
        textClarityTooltip:
            "Presenting information clearly and understandably, making your content straightforward and easy to grasp for your audience.",
        textTalkTimeTooltip: "The amount of time the speaker spent talking",
        textRepetitiveWordsTooltip:
            "Words that are repeated that has already been said",
        textFillerWordsTooltip:
            "Words or phrases that are used to fill pauses in speech",
        textAhCountTooltip: "The number of times the speaker used filler words",
        textMoreTokensDecOne: "1 Token = 10 interview questions",
        textMoreTokensDecTwo: "Answer up to 3x questions",
        textMoreTokensDecThree: "Advanced reporting",
        textPaymentSuccess: "Payment Successful",
        textTokensUpgraded: "Your tokens have been upgraded",
        textSubscribed: "Thank you! You've successfully subscribed.",
        textFreeTokens: "Your tokens have been upgraded with 3 days free trial",
        textUpcoming: "Upcoming",
        placeholderEmail: "email@domain.com",
        areYouSure: "Are you sure ?",
        textMeetLeaveInterview: "Are you sure you want to end the interview?",
        textMeetDisconnected:
            "The server has been disconnected. Would you like to resume?",

        textAskToSwitchQuestion:
            "Completed your response? Ready for the next question?",
        textAreYouComplete: "Completed your response?",
        textMeetAddDescription: "Enter your job description",
        textMeetStartInterview: "start interview",
        textMeetInterviewEvaluating:
            "We are currently in the evaluation process <br/> and will notify you through a notification once it is complete.",
        textMeetFeedbackText:
            "How would you describe your experience during the interview session?",
        textMeetFeedbackMoreLike: "More like this",
        textMeetFeedbackNotSatisfied: "Not satisfied",
        textMeetFeedbackSkip: "Skip for now",
        textMeetFeedbackAck: "Thank you for sharing your feedback!",
        textMeetErrorTitle: "Something went wrong",
        textMeetErrorLoading1:
            "We apologize for any inconvenience caused! It appears that there was a technical glitch on our side during the interview loading process. ",
        textMeetErrorLoading2:
            " Would you be willing to attempt the process again?",
        textMeetErrorDescription:
            "An error has occurred, and we are currently attempting to establish a connection with the server.",
        errorEmailRequired: "Email is required",
        errorEmailInvalid: "Email is invalid",
        errorEmailPwInvalid: "Invalid email or password",
        errorPwLength: "Password should be at-least 6 characters",
        errorPwRequired: "Password is required",
        errorPwOldRequired: "Current Password is required",
        errorPwdInvalid: "Invalid Credentials",
        errorFirstNameRequired: "First Name is required",
        errorLastNameRequired: "Last Name is required",
        errorNoAudioDevices: "No audio input devices found",
        errorDataNull: "Data is null or missing",
        errorFetchData: "Error fetching data:",
        interviewTimoutMessage:
            "Sorry your time is up. Thank you for your time. Goodbye.",
        userNotReponding:
            "Sorry, I could not capture your response. Wanna go again?",
        wannaGoAgain: "Wanna go again?",
        toastPwReset: "Password reset email sent",
        toastInvalidEmail: "Invalid or unregistered email",
        toastAccNotFound: "Account not found",
        toastNoUserFound: "User not found. Please use a registered account",
        toastInvalidCredentials: "Invalid email or password",
        toastNoEmailFound:
            "Invalid or unregistered email. Please use a registered email",
        toastUserAlreadyExists: "User already exists",
        toastUserCreated: "User created successfully",
        notificationReportReady: "Interview evaluation report is ready!!!",
        notAnswered: "Candidate not provided any answer for this question",
        summaryFeedback: "Summary Feedback",
        transcript: "Transcript",
        choosePlan: "Choose your subscription",
        changePlan: "Change your subscription",
        planCancel: "No commission fee or contract, You can cancel anytime.",
        Purchases: "Purchases",
        manageMember: "Manage Membership",
        purchasesDescription: "You don’t have any purchases yet",
        benefits: "Benefits",
        oneMonthTrail: "1 Month-3 days free trial",
        oneMonth: "1 Month",
        threeMonth: "3 Month",
        tokenLeft: "Tokens Left",
        tokenLeftDescription: " You need more tokens to \n complete the streak",
        next: "Next",
        previous: "Previous",
        page: "page",
        of: "of",
        open: "Open",
        noBillingHistory: "No billing history available",
        approximateTime: "Approximate Time : ",
        offerDescription: "Don't miss the Year-end offer Up to 32% OFF!",
        updgradeNow: "Upgrade Now",
        timeOver: "Sorry, your time is up. Please wait for the next question.",
        preparationTime: "Preparation Time",
        continue: "Continue",
        support: "Support",
        Subscription: "Subscription",
        submit: "Submit",
        serverDownTxt: "Server Disconnected!",
        status: "Status",
        successfullyTicketCreated: "Created a ticket for you succesfully!",
        ticketNumber: "Your ticket number is",
        agentTouch: "An agent will be in touch in the next 24hr.",
        goBackBtn: "Go Back",
        excuse: "Forgive us for the delay while we help everyone in order",
        errorInContent: "Error while loading content",
        referralDiscount1: "Get 5% discount for each referral",
        referralDiscount2:
            "For every colleague or follower who signs up and records a meeting,",
        referralDiscount3: "You get 5% discount, up to 4 weeks.",
        linkPrivacyPolicy: "https://talktune.ai/privacy-policy",
        linkTermsConditions: "https://talktune.ai/terms-service",
        interviewCenterDescription: "Choose your profession to begin practicing",
        logoutConfirmation: "Are you sure you want to logout?",
    };

    return selectedStrings;
}

export default useSelectedStrings;
